name: IPTV Otomatik Guncelleme

on:
  workflow_dispatch: # Manuel tetikleme için
  schedule:
    - cron: '0 */6 * * *' # Her 6 saatte bir otomatik çalışır
  push:
    paths:
      - 'script.py'

jobs:
  run-script:
    runs-on: ubuntu-latest
    # GitHub'a yazma izni vermek için bu kısım kritik:
    permissions:
      contents: write

    steps:
    - name: Kodu çek
      uses: actions/checkout@v4

    - name: Python kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp

    - name: Scripti çalıştır
      run: python script.py

    - name: Değişiklikleri Kontrol Et ve Yukle
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Python kodun hangi dosyayı üretiyorsa onu ekle (Hepsini garantiye alalım)
        git add *.m3u || echo "M3U dosyası bulunamadı"
        
        # Değişiklik var mı kontrol et
        if git diff --staged --quiet; then
          echo "Değişiklik yok, işlem sonlandırılıyor."
        else
          git commit -m "Otomatik Güncelleme: $(date +'%Y-%m-%d %H:%M') [ci skip]"
          git push origin HEAD:${{ github.ref }}
        fi
