name: Python Async IPTV Playlist Workflow

on:
  push:
    paths:
      - script.py
      - .github/workflows/python-app.yml
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp

    - name: Run script
      run: python script.py

    - name: Upload filtered M3U output
      uses: actions/upload-artifact@v4
      with:
        name: filtered_playlist
        path: filtered_playlist.m3u
