name: Python Async IPTV Playlist Commit Workflow

on:
  workflow_dispatch:
  push:
    paths:
      - script.py
      - .github/workflows/python-async-iptv-commit.yml

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu çek
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Tüm geçmişi çekmek için

    - name: Python kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp

    - name: Scripti çalıştır
      run: python script.py

    - name: Değişiklikleri repoya ekle ve pushla
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add filtered_playlist.m3u
        git commit -m "Otomatik: filtered_playlist.m3u güncellendi [ci skip]" || echo "Commit edilecek değişiklik yok."
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD:${{ github.ref }}
